---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --non-interactive

script:
  - yarn lint:hbs
  - yarn lint:js
  - yarn test

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info

env:
  - COVERAGE=true CODECLIMATE_REPO_TOKEN=9e087f07cf44e07584de87390bc3e55de61e1523afe675df9c8f4d6ba7fba38b
